<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:17:05.
 */
class pagseguroResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pagseguroResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pagseguroResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pagseguroResource::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pagseguroResource::needPayment
     * @todo   Implement testNeedPayment().
     */
    public function testNeedPayment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pagseguroResource::compra
     * @todo   Implement testCompra().
     */
    public function testCompra() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pagseguroResource::assinatura
     * @todo   Implement testAssinatura().
     */
    public function testAssinatura() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pagseguroResource::retorno
     * @todo   Implement testRetorno().
     */
    public function testRetorno() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
