<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:32.
 */
class ECITest extends PHPUnit_Framework_TestCase {

    /**
     * @var ECI
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ECI;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ECI::value
     * @todo   Implement testValue().
     */
    public function testValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ECI::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
